name: Determine event source

on:
  push:
    # If you don't specify a branch, it will also trigger on tags. Which may not be desirable when also triggering on release events.
    branches:
      - "*"
  workflow_dispatch:
  release:
    published:

jobs:
  where-did-you-come-from:
    runs-on: ubuntu-latest
    steps:
      - name: Determine source
        run: |
          echo "Event name: ${{ github.event_name }}"
          echo "Event Head Ref: ${{ github.head_ref }}"
          echo "Event Ref: ${{ github.ref }}"
          echo "Event Ref Type: ${{ github.ref_type }}"
          echo "Event Ref Name: ${{ github.ref_name }}"
          echo "Event Pre-Release: ${{ github.event.release.prerelease }}"
          echo "Event Release Tag: ${{ github.event.release.tag_name }}"

          # looks like master_branch is deprecated, but it's still available
          printf "Main Branch: \n\tgithub.event.repository.master_branch: ${{ github.event.repository.master_branch }}\n\tgithub.event.repository.default_branch: ${{ github.event.repository.default_branch }}"
      - name: Whole dang thing
        env:
          GHA_OBJ: ${{ toJson(github) }}
        run: |
          echo $GHA_OBJ | jq .

          