name: Determine event source

on:
  push:
    # If you don't specify a branch, it will also trigger on tags. Which may not be desirable when also triggering on release events.
    branches:
      - "*"
  workflow_dispatch:
  release:
    types: [published]

jobs:
  determine_source:
    runs-on: ubuntu-latest
    name: Determine source
    steps:
      - name: Where did you come from?
        run: |
          echo "Event name: ${{ github.event_name }}"
          echo "Event Head Ref: ${{ github.head_ref }}"
          echo "Event Ref: ${{ github.ref }}"
          echo "Event Ref Type: ${{ github.ref_type }}"
          echo "Event Ref Name: ${{ github.ref_name }}"
          echo "Default Branch: ${{ github.event.repository.default_branch }}"
          echo "Event Pre-Release: ${{ github.event.release.prerelease }}"
          echo "Event Release Tag: ${{ github.event.release.tag_name }}"
      - name: Where did you go?
        run: |
          if [[ "${{ github.ref_type }}" == "tag" ]]; then
            if [[ "${{ github.event.release.prerelease }}" == "true" ]]; then
              echo "This event was triggered by a pre-release tag."
            else
              echo "This event was triggered by a release tag."
            fi
          elif [[ "${{ github.ref_type }}" == "branch" ]]; then
            if [[ "${{ github.event.repository.default_branch }}" == "${{ github.ref_name }}" ]]; then
              echo "This event was triggered by a push to the default branch (${{ github.ref_name }})."
            else
              echo "This event was triggered by a push to branch \"${{ github.ref_name }}\"."
            fi
          elif [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            echo "This event was triggered by a workflow dispatch on branch \"${{ github.ref_name }}\"."
          else
            echo "You are on something else"
          fi
      - name: Where did you come from Cotton Eye Joe?
        env:
          GHA_OBJ: ${{ toJson(github) }}
        run: |
          echo $GHA_OBJ | jq .

          