name: Determine event source

on:
  push:
  workflow_dispatch:
  release:
    published:

jobs:
  where-did-you-come-from:
    runs-on: ubuntu-latest
    steps:
      - name: Determine source
        run: |
          echo "Event Json: ${{ github.event }}"
          echo "Event name: ${{ github.event.Name }}"
          echo "Event Head Ref: ${{ github.event.HeadRef }}"
          echo "Event Ref: ${{ github.event.Ref }}"
          echo "Event Ref Type: ${{ github.event.RefType }}"

          