name: Determine event source

on:
  push:
  workflow_dispatch:
  release:
    published:

jobs:
  where-did-you-come-from:
    runs-on: ubuntu-latest
    steps:
      - name: Determine source
        run: |
          echo "Event name: ${{ github.event_name }}"
          echo "Event Head Ref: ${{ github.head_ref }}"
          echo "Event Ref: ${{ github.ref }}"
          echo "Event Ref Type: ${{ github.ref_type }}"
          echo "Event Ref Name: ${{ github.ref_name }}"
      - name: Whole dang thing
        run: |
          jq '${{ toJson(github) }}'

          